# for jekyll-github-metadata
repsitory: trasparente/beacon

# To have /collection/page/ links
permalink: pretty

# Plugins list
plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-github-metadata

# Output collection
collections:
  docs:
    output: true

# Defaults
defaults:
  # Set default layout in collections
  - scope:
      type: docs
    values:
      layout: default

# Css style
# css:
#   small:
#     screen: 40em
#   width:
#     container: 40em
#   bg:
#     main: White
#     html: WhiteSmoke
#     navbar: WhiteSmoke
#   color:
#     main: Black
#     link:
#       main: MediumBlue
#       hover: Crimson
#       active: transparent
#     font:
#       main: sans-serif
#       headings: serif

# Timezone
timezone: Europe/Rome