# for jekyll-github-metadata
repsitory: trasparente/beacon

# To have /collection/page/ links
permalink: pretty

# Plugins list
plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-github-metadata

# Output collection
collections:
  docs:
    output: true

# Defaults
defaults:
  # Set default layout in collections
  - scope:
      type: docs
    values:
      layout: default

# css:
#   small:
#     screen: 40em
#   width:
#     container: 40em
#   bg:
#     sections:
#       - LightCyan
#       - OldLace
#     blockquote: WhiteSmoke
#     main: White
#     html: WhiteSmoke
#     navbar: WhiteSmoke
#     code: WhiteSmoke
#   sections:
#     - OldLace
#     - Lavender
#   border:
#     blockquote:
#       left: "5px solid red"
#   classes:
#     - info:
#         background: LightCyan
#     - warning:
#         background: OldLace
#   color:
#     main: Black
#     muted: Grey
#     link:
#       main: MediumBlue
#       hover: Crimson
#       active: transparent
#   font:
#     main: sans-serif
#     headings: serif

# Timezone
timezone: Europe/Rome